Repository Haru-Kobayashi073/Shibuya-Buddy, pull requests merged in 2025-01, with the labels that each got.

#108 エラーページの追加
  assets/images/error.png
  lib/error_page.dart
  lib/gen/assets.gen.dart
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
Labels: 🎉 new feature

#107 CurrentAuthUserの過度なデータ保持をリファクタ
  lib/error_page.dart
  lib/infrastructure/file/file_data_source.dart
  lib/infrastructure/firebase/current_auth_user.dart
  lib/infrastructure/firebase/current_auth_user.g.dart
  lib/presentation/mypage/my_page_notifier.dart
  lib/presentation/register_profile/register_profile_page_notifier.dart
Labels: 🐛 bugf fix, 🧹 refactoring

#110 課金誘導ダイアログを実装
  lib/presentation/bill_details/bill_details_page.dart
  lib/utils/routes/app_router.dart
  lib/utils/routes/app_router.g.dart
  lib/utils/routes/routes.dart
Labels: 🎉 new feature

#112 Feature/license page
  ios/Podfile.lock
  lib/presentation/mypage/my_page.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎉 new feature

#119 Androidで利用規約にアクセスできない問題を修正
  android/app/src/main/AndroidManifest.xml
  lib/i18n/strings.g.dart
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/infrastructure/file/file_data_source.g.dart
  lib/presentation/mypage/my_page_notifier.g.dart
  lib/presentation/register_profile/register_profile_page_notifier.g.dart
Labels: 🐛 bugf fix

#122 アカウント連携解除時に出てくるダイアログの変更
  lib/presentation/account/account_page.dart
Labels: 🎉 new feature

#118 AndroidStudioをアップデートした際に発生するエラーを修正
  android/gradle/wrapper/gradle-wrapper.properties
  android/settings.gradle
Labels: 🐛 bugf fix

#123 ブックマークの切り替えを実装
  lib/domain/entities/plan.dart
  lib/domain/entities/plan.freezed.dart
  lib/domain/entities/plan.g.dart
  lib/domain/repositories/plan_repository.dart
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/infrastructure/file/file_data_source.dart
  lib/infrastructure/plan/plan_data_source.dart
  lib/infrastructure/plan/plan_data_source.g.dart
  lib/presentation/buddy_chat/buddy_chat_page.dart
  lib/presentation/components/plan_card.dart
  lib/presentation/home/components/recent_plans_section.dart
  lib/presentation/home/home_page_notifier.dart
  lib/presentation/my_plan/bookmark_plans_tab_view.dart
  lib/presentation/my_plan/created_plans_tab_view.dart
  lib/presentation/my_plan/mock.dart
  lib/presentation/my_plan/my_plan_page.dart
  lib/presentation/my_plan/my_plan_page_notifier.dart
  lib/presentation/plan_detail/plan_detail_page_notifier.dart
  lib/presentation/plan_detail/plan_detail_page_notifier.g.dart
Labels: 🎉 new feature, 🧹 refactoring

#125 ランキングロジックの実装
  firebase.json
  functions/.gitignore
  functions/package-lock.json
  functions/package.json
  functions/src/index.ts
  functions/tsconfig.json
  ios/Podfile
  ios/Podfile.lock
  lib/i18n/strings.g.dart
  lib/infrastructure/file/file_data_source.g.dart
  lib/infrastructure/plan/plan_data_source.dart
  lib/infrastructure/plan/plan_data_source.g.dart
  lib/infrastructure/topic/topic_data_source.dart
  lib/presentation/components/plan_card.dart
  lib/presentation/components/ranking_label.dart
  lib/presentation/components/topic_card.dart
  lib/presentation/home/components/popular_plans_carousel.dart
  lib/presentation/home/components/popular_topics_section.dart
  lib/presentation/home/home_page.dart
  lib/presentation/home/home_page_notifier.dart
  lib/presentation/home/home_page_notifier.g.dart
  lib/presentation/my_plan/my_plan_page_notifier.g.dart
  lib/presentation/plan_detail/plan_detail_page_notifier.g.dart
  lib/presentation/popular_plans/popular_plans_page.dart
  lib/presentation/popular_topics/popular_topics_page.dart
  lib/utils/routes/app_router.dart
  lib/utils/routes/app_router.g.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎉 new feature

#130 リモートのトピック一覧を取得・表示
  lib/domain/entities/topic.dart
  lib/domain/entities/topic.freezed.dart
  lib/domain/entities/topic.g.dart
  lib/i18n/strings.g.dart
  lib/infrastructure/plan/plan_data_source.dart
  lib/infrastructure/plan/plan_data_source.g.dart
  lib/infrastructure/topic/topic_data_source.dart
  lib/infrastructure/topic/topic_data_source.g.dart
  lib/presentation/buddy_chat/buddy_chat_page_notifier.dart
  lib/presentation/buddy_chat/buddy_chat_page_notifier.g.dart
  lib/presentation/components/plan_card.dart
  lib/presentation/components/topic_card.dart
  lib/presentation/create_plan/components/selection_modal.dart
  lib/presentation/create_plan/create_plan_notifier.dart
  lib/presentation/create_plan/create_plan_notifier.g.dart
  lib/presentation/create_plan/create_plan_page.dart
  lib/presentation/create_plan/create_plan_state.dart
  lib/presentation/create_plan/create_plan_state.freezed.dart
  lib/presentation/home/components/popular_topics_section.dart
  lib/presentation/home/home_page.dart
  lib/presentation/home/home_page_notifier.dart
  lib/presentation/home/home_page_notifier.g.dart
  lib/presentation/plans_related_in_topic/plans_related_in_topic_page.dart
  lib/presentation/plans_related_in_topic/plans_related_in_topic_page_notifier.dart
  lib/presentation/plans_related_in_topic/plans_related_in_topic_page_notifier.g.dart
  lib/presentation/popular_topics/popular_topics_page.dart
  lib/utils/routes/app_router.dart
  lib/utils/routes/app_router.g.dart
  lib/utils/routes/routes.dart
Labels: 🎉 new feature, 🧹 refactoring

#133 マップページを実装
  .gitignore
  ios/Podfile
  ios/Podfile.lock
  ios/Runner/AppDelegate.swift
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/presentation/map/map_page.dart
  lib/presentation/plan_detail/plan_detail_page.dart
  lib/utils/routes/app_router.dart
  lib/utils/routes/app_router.g.dart
  lib/utils/routes/routes.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎉 new feature

#134 ロード画面の変更
  assets/lottie/Animation - 1736996724199.json
  lib/i18n/strings.g.dart
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/presentation/components/loading_overlay.dart
Labels: 🐛 bugf fix

#136 PlaceCardのオーバーフローを修正
  lib/presentation/components/place_card.dart
Labels: 🐛 bugf fix

#137 アカウントステータスのOverflowを修正
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/presentation/components/simple_text_field.dart
  lib/presentation/mypage/components/account_status.dart
  lib/presentation/mypage/edit_profile/edit_profile_page.dart
  lib/presentation/register_profile/register_profile_page.dart
  lib/utils/validator.dart
Labels: 🐛 bugf fix

#139 RecentPlanのコンポーネントのOverflowを修正
  lib/presentation/home/components/recent_plan.dart
Labels: 🐛 bugf fix

#140 info.plistを多言語化
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/en.lproj/InfoPlist.strings
  ios/Runner/ja.lproj/InfoPlist.strings
  ios/Runner/ja.lproj/LaunchScreen.strings
  ios/Runner/ja.lproj/Main.strings
  ios/Runner/zh-Hans.lproj/InfoPlist.strings
  ios/Runner/zh-Hans.lproj/LaunchScreen.strings
  ios/Runner/zh-Hans.lproj/Main.strings
  ios/Runner/zh-Hant.lproj/InfoPlist.strings
  ios/Runner/zh-Hant.lproj/LaunchScreen.strings
  ios/Runner/zh-Hant.lproj/Main.strings
Labels: 🎁 release

#138 メールの認証をできていない場合に認証ページに遷移する機能の追加
  ios/Podfile.lock
  lib/gen/assets.gen.dart
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/presentation/email_verification/email_verification_page.dart
  lib/presentation/sign_in/sign_in_page.dart
  lib/presentation/sign_in/sign_in_page_notifier.dart
  lib/presentation/sign_in/sign_in_page_notifier.g.dart
  lib/presentation/sign_up/sign_up_page.dart
  lib/start_up_page.dart
  lib/utils/routes/app_router.dart
  lib/utils/routes/app_router.g.dart
  lib/utils/routes/routes.dart
Labels: 🐛 bugf fix

#135 MyPlanのCreatedTabViewに遷移する機能の実装
  lib/presentation/home/components/section_title.dart
  lib/presentation/my_plan/my_plan_page.dart
  lib/presentation/my_plan/my_plan_page_notifier.dart
Labels: 🎉 new feature

#146 #131実装に際して起きた不具合の修正
  lib/presentation/home/components/recent_plans_section.dart
  lib/presentation/home/components/section_title.dart
Labels: 🐛 bugf fix

#153 マイプランページのタグがオーバーフローする不具合
  lib/presentation/components/row_category_tags.dart
Labels: 🐛 bug fix

#157 韓国語対応
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_kr.g.dart
  lib/i18n/strings_kr.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/presentation/change_language/change_language_page.dart
  lib/presentation/sign_in/sign_in_page.dart
  lib/utils/providers/locale/locale_service.dart
  lib/utils/providers/locale/locale_service.g.dart
  lib/utils/translate_prompt.dart
Labels: 🎉 new feature

#160 プレミアムプランの有効期限の表示位置の変更
  lib/presentation/mypage/components/account_status.dart
Labels: 🐛 bug fix

#151 課金詳細ページのoverflow対策
  lib/gen/assets.gen.dart
  lib/i18n/strings.g.dart
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_kr.g.dart
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/presentation/bill_details/components/plan_table.dart
  lib/utils/providers/locale/locale_service.g.dart
Labels: 🐛 bug fix, 📱Android

#164 電話番号(SMS)認証を実装
  lib/domain/repositories/authentication_repository.dart
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_ko.g.dart
  lib/i18n/strings_ko.i18n.json
  lib/i18n/strings_kr.g.dart
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/infrastructure/authentication/authentication_data_source.dart
  lib/infrastructure/authentication/authentication_data_source.g.dart
  lib/presentation/email_verification/email_verification_page.dart
  lib/presentation/phone_number_input/phone_number_input_page.dart
  lib/presentation/phone_number_input/phone_number_input_page_notifier.dart
  lib/presentation/phone_number_input/phone_number_input_page_notifier.g.dart
  lib/presentation/phone_number_input/phone_number_input_state.dart
  lib/presentation/phone_number_input/phone_number_input_state.freezed.dart
  lib/presentation/sms_verification/sms_verification_page.dart
  lib/presentation/sms_verification/sms_verification_page_notifier.dart
  lib/presentation/sms_verification/sms_verification_page_notifier.g.dart
  lib/presentation/sms_verification/sms_verification_state.dart
  lib/presentation/sms_verification/sms_verification_state.freezed.dart
  lib/start_up_page.dart
  lib/utils/providers/locale/locale_service.g.dart
  lib/utils/routes/app_router.dart
  lib/utils/routes/app_router.g.dart
  lib/utils/routes/routes.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎉 new feature

#168 未実装の機能の一時削除
  lib/presentation/components/place_card.dart
  lib/presentation/my_plan/bookmark_plans_tab_view.dart
  lib/presentation/my_plan/created_plans_tab_view.dart
  lib/presentation/mypage/my_page.dart
  lib/presentation/plan_detail/plan_detail_page.dart
  lib/presentation/sign_in/sign_in_page.dart
Labels: 🧹 refactoring

#165 ユーザーの削除機能の実装
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_ko.g.dart
  lib/i18n/strings_ko.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/presentation/account/account_page.dart
  lib/presentation/account/account_page_notifier.dart
Labels: 🎉 new feature

#169 価格設定の見直し
  .github/workflows/ios-deliver.yml
  android/app/google-services-prod.json
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/GoogleService-Info-prod.plist
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_ko.g.dart
  lib/i18n/strings_ko.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/presentation/email_verification/email_verification_page.dart
  lib/presentation/phone_number_input/phone_number_input_page.dart
  lib/presentation/sms_verification/sms_verification_page.dart
  lib/utils/billing_grade_options.dart
Labels: 🎁 release

#171 リリース用にprofileを変更
  ios/Runner.xcodeproj/project.pbxproj
Labels: 🎁 release

#173 アイコン生成の修正
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  pubspec.yaml
Labels: 🎁 release

#191 Androidでのアカウント連携の修正
  android/.gitignore
  release.jks
Labels: 🐛 bug fix, 📱Android

#194 refresh機能の作成
  lib/presentation/my_plan/bookmark_plans_tab_view.dart
  lib/presentation/my_plan/created_plans_tab_view.dart
Labels: 🎉 new feature

#195 ソーシャルアカウントのログインを修正
  lib/presentation/sign_in/sign_in_page_notifier.dart
Labels: 🐛 bug fix, 📱iPhone, 📱Android

#198 Fix/slang
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ko.g.dart
  lib/i18n/strings_ko.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
Labels: 🐛 bug fix
