Repository Haru-Kobayashi073/Shibuya-Buddy, pull requests merged in 2025-02, with the labels that each got.

#210 メール認証ページに遷移時、自動でメールを一度送信するよう修正
  lib/gen/assets.gen.dart
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_ko.g.dart
  lib/i18n/strings_ko.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/infrastructure/authentication/authentication_data_source.g.dart
  lib/presentation/email_verification/email_verification_page.dart
  lib/presentation/email_verification/email_verification_page_notifier.dart
  lib/presentation/email_verification/email_verification_page_notifier.g.dart
  lib/presentation/home/home_page_notifier.g.dart
  lib/utils/providers/in_app_purchase/in_app_purchase_service.g.dart
Labels: 🎉 new feature

#206 画像検索コスト削減のための最適化
  lib/presentation/buddy_chat/buddy_chat_page_notifier.dart
Labels: 🧹 refactoring

#211 設定している言語に合わせて電話番号のISOコードを設定
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_ko.g.dart
  lib/i18n/strings_ko.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/presentation/email_verification/email_verification_page_notifier.g.dart
  lib/presentation/phone_number_input/phone_number_input_page.dart
  lib/presentation/phone_number_input/phone_number_input_page_notifier.dart
  lib/presentation/phone_number_input/phone_number_input_page_notifier.g.dart
  lib/presentation/phone_number_input/phone_number_input_page_state.dart
  lib/presentation/phone_number_input/phone_number_input_page_state.freezed.dart
  lib/presentation/phone_number_input/phone_number_input_state.dart
  lib/presentation/phone_number_input/phone_number_input_state.freezed.dart
  lib/utils/validator.dart
Labels: 🎉 new feature, 🧹 refactoring

#215 アプリ初回起動時に言語選択モーダルを表示する
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_ko.g.dart
  lib/i18n/strings_ko.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/presentation/buddy_chat/buddy_chat_page_notifier.g.dart
  lib/presentation/change_language/change_language_page.dart
  lib/presentation/components/change_language_dialog.dart
  lib/presentation/sign_in/sign_in_page.dart
  lib/presentation/sign_in/sign_in_page_notifier.dart
  lib/presentation/sign_in/sign_in_page_notifier.g.dart
  lib/utils/providers/shared_preferences/shared_preferences_config.dart
  lib/utils/providers/shared_preferences/shared_preferences_service.dart
  lib/utils/providers/shared_preferences/shared_preferences_service.g.dart
Labels: 🎉 new feature

#217 Android端末でサインインページ表示時はAppleサインインを表示しない
  lib/presentation/account/account_page.dart
  lib/presentation/sign_in/sign_in_page.dart
Labels: 🎉 new feature, 📱Android

#216 AppCheckの導入
  .vscode/launch.json
  android/app/build.gradle
  android/app/google-services-prod.json
  functions/package-lock.json
  functions/package.json
  functions/src/index.ts
  ios/Podfile.lock
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎉 new feature

#220 [iOS] 標準の暗号化のみを使用していることを明記する
  ios/Runner/Info.plist
Labels: 🎁 release, 📱iPhone

#224 ATT対応
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/Runner/en.lproj/InfoPlist.strings
  ios/Runner/ja.lproj/InfoPlist.strings
  ios/Runner/zh-Hans.lproj/InfoPlist.strings
  ios/Runner/zh-Hant.lproj/InfoPlist.strings
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎁 release, 📱iPhone

#226 production用のProfileに切り替え
  ios/Runner.xcodeproj/project.pbxproj
Labels: 🎁 release, 📱iPhone

#229 トピックの多言語対応
  lib/domain/entities/plan.dart
  lib/domain/entities/plan.freezed.dart
  lib/domain/entities/plan.g.dart
  lib/domain/entities/topic.dart
  lib/domain/entities/topic.freezed.dart
  lib/domain/entities/topic.g.dart
  lib/infrastructure/gemini/gemini_data_source.dart
  lib/presentation/buddy_chat/components/message_card.dart
  lib/presentation/components/plan_card.dart
  lib/presentation/components/row_category_tags.dart
  lib/presentation/components/topic_card.dart
  lib/presentation/create_plan/components/topic_chip_field.dart
  lib/presentation/create_plan/create_plan_page.dart
  lib/presentation/home/components/category_tags.dart
  lib/presentation/home/components/popular_plans_carousel.dart
  lib/presentation/home/components/recent_plan.dart
  lib/presentation/plan_detail/components/plan_header.dart
  lib/presentation/plan_detail/plan_detail_page.dart
  lib/utils/providers/locale/locale_service.dart
  lib/utils/providers/locale/locale_service.g.dart
  lib/utils/translate_prompt.dart
Labels: 🎉 new feature

#230 課金詳細ページの購入の復元の説明を外部ブラウザに移行
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_ko.g.dart
  lib/i18n/strings_ko.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/presentation/bill_details/bill_detail_page_notifier.dart
  lib/presentation/bill_details/bill_detail_page_notifier.g.dart
  lib/presentation/bill_details/components/restore_purchase_section.dart
Labels: 🎉 new feature

#233 Loggerのセットアップ
  assets/images/error-image.svg
  assets/images/error.png
  lib/gen/assets.gen.dart
  lib/i18n/strings.g.dart
  lib/infrastructure/gemini/gemini_data_source.g.dart
  lib/presentation/account/account_page_notifier.dart
  lib/presentation/bill_details/bill_detail_page_notifier.dart
  lib/presentation/bill_details/bill_detail_page_notifier.g.dart
  lib/presentation/buddy_chat/buddy_chat_page.dart
  lib/presentation/buddy_chat/buddy_chat_page_notifier.dart
  lib/presentation/components/error_view.dart
  lib/presentation/components/radio_button_with_text.dart
  lib/presentation/create_plan/create_plan_notifier.dart
  lib/presentation/create_plan/create_plan_page.dart
  lib/presentation/email_verification/email_verification_page_notifier.dart
  lib/presentation/home/home_page.dart
  lib/presentation/home/home_page_notifier.dart
  lib/presentation/my_plan/my_plan_page.dart
  lib/presentation/my_plan/my_plan_page_notifier.dart
  lib/presentation/mypage/edit_profile/edit_profile_page.dart
  lib/presentation/mypage/edit_profile/edit_profile_page_notifier.dart
  lib/presentation/mypage/my_page.dart
  lib/presentation/phone_number_input/phone_number_input_page_notifier.dart
  lib/presentation/plan_detail/plan_detail_page.dart
  lib/presentation/plan_detail/plan_detail_page_notifier.dart
  lib/presentation/plans_related_in_topic/plans_related_in_topic_page.dart
  lib/presentation/plans_related_in_topic/plans_related_in_topic_page_notifier.dart
  lib/presentation/register_profile/register_profile_page_notifier.dart
  lib/presentation/reset_password/reset_password_page_notifier.dart
  lib/presentation/sign_in/sign_in_page_notifier.g.dart
  lib/presentation/sign_up/sign_up_page_notifier.dart
  lib/presentation/sms_verification/sms_verification_page_notifier.dart
  lib/utils/custom_logger.dart
  lib/utils/providers/current_user/current_user.dart
  lib/utils/providers/in_app_purchase/in_app_purchase_service.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎉 new feature

#239 SMSコード送信時にOverlayLoadingが出ない問題を修正
  lib/presentation/phone_number_input/phone_number_input_page_notifier.dart
Labels: 🐛 bug fix

#240 タイトルをユニークに変える
  lib/utils/translate_prompt.dart
Labels: 🎉 new feature, 🧹 refactoring

#241 ソーシャルログインの修正
  lib/presentation/register_profile/register_profile_page.dart
  lib/presentation/register_profile/register_profile_page_notifier.dart
  lib/presentation/sign_in/sign_in_page_notifier.dart
  lib/presentation/sms_verification/sms_verification_page_notifier.dart
  lib/start_up_page.dart
Labels: 🐛 bug fix, 📱iPhone, 📱Android

#252 DevelopでAppCheckを適用
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  ios/Podfile.lock
  ios/Runner/AppDelegate.swift
  pubspec.lock
  pubspec.yaml
Labels: 🎉 new feature

#250 認証のフローを見直し
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_ko.g.dart
  lib/i18n/strings_ko.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/infrastructure/gemini/gemini_data_source.g.dart
  lib/presentation/account/account_page.dart
  lib/presentation/authentication/authentication_page.dart
  lib/presentation/authentication/authentication_page_notifier.dart
  lib/presentation/authentication/authentication_page_notifier.g.dart
  lib/presentation/buddy_chat/buddy_chat_page_notifier.g.dart
  lib/presentation/complete_send_email/complete_send_email_page.dart
  lib/presentation/components/change_language_dialog.dart
  lib/presentation/email_verification/email_verification_page.dart
  lib/presentation/home/home_page_notifier.g.dart
  lib/presentation/sign_in/sign_in_page_notifier.g.dart
  lib/presentation/sign_up/sign_up_page.dart
  lib/presentation/sign_up/sign_up_page_notifier.dart
  lib/presentation/sign_up/sign_up_page_notifier.g.dart
  lib/start_up_page.dart
  lib/utils/providers/geofence/geofence_service.g.dart
  lib/utils/routes/app_router.dart
  lib/utils/routes/app_router.g.dart
  lib/utils/routes/routes.dart
Labels: 🐛 bug fix

#248 プランのブックマーク機能の修正
  functions/src/index.ts
  lib/domain/entities/plan.dart
  lib/domain/entities/plan.freezed.dart
  lib/domain/entities/plan.g.dart
  lib/i18n/strings.g.dart
  lib/presentation/my_plan/my_plan_page_notifier.dart
  lib/presentation/plan_detail/plan_detail_page.dart
  lib/presentation/plan_detail/plan_detail_page_notifier.dart
  lib/presentation/plan_detail/plan_detail_page_state.dart
  lib/presentation/plan_detail/plan_detail_page_state.freezed.dart
Labels: 🐛 bug fix

#247 Admobの設定
  .github/workflows/ios-deliver.yml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/i18n/strings.g.dart
  lib/main.dart
  lib/presentation/bill_details/bill_detail_page_notifier.dart
  lib/presentation/map/map_page.dart
  lib/presentation/map/map_page_notifier.dart
  lib/presentation/map/map_page_notifier.g.dart
  lib/presentation/map/map_page_state.dart
  lib/presentation/map/map_page_state.freezed.dart
  lib/presentation/plan_detail/plan_detail_page.dart
  lib/presentation/plan_detail/plan_detail_page_notifier.dart
  lib/presentation/plan_detail/plan_detail_page_notifier.g.dart
  lib/utils/providers/ad_helper/ad_helper.dart
  lib/utils/providers/ad_helper/ad_helper.g.dart
  lib/utils/providers/ad_helper/ad_helper_state.dart
  lib/utils/providers/ad_helper/ad_helper_state.freezed.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎉 new feature

#254 プラン作成時のロード画面の実装
  assets/lottie/Animation - 1739357512444.json
  lib/gen/assets.gen.dart
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_ko.g.dart
  lib/i18n/strings_ko.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/infrastructure/gemini/gemini_data_source.dart
  lib/presentation/buddy_chat/buddy_chat_page.dart
  lib/presentation/buddy_chat/buddy_chat_page_notifier.dart
  lib/presentation/components/create_plan_loading/create_loading_notifier.dart
  lib/presentation/components/create_plan_loading/create_loading_notifier.g.dart
  lib/presentation/components/create_plan_loading/create_loading_state.dart
  lib/presentation/components/create_plan_loading/create_loading_state.freezed.dart
  lib/presentation/components/create_plan_loading/create_loading_view.dart
  lib/presentation/components/create_plan_loading/loading_text.dart
Labels: 🎉 new feature

#259 ログイン時にoverlayLoadingを出す処理を追加
  ios/Runner/Info.plist
  lib/presentation/authentication/authentication_page_notifier.dart
Labels: 🎉 new feature

#265 プランを利用したかわかるバッジの実装
  functions/src/index.ts
  lib/domain/entities/plan.dart
  lib/domain/entities/plan.freezed.dart
  lib/domain/entities/plan.g.dart
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_ko.g.dart
  lib/i18n/strings_ko.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/infrastructure/place_detail/place_detail_data_source.g.dart
  lib/main.dart
  lib/presentation/authentication/authentication_page_notifier.g.dart
  lib/presentation/buddy_chat/buddy_chat_page_notifier.g.dart
  lib/presentation/components/create_plan_loading/create_loading_notifier.g.dart
  lib/presentation/plan_detail/components/have_used_plan_question_dialog.dart
  lib/presentation/plan_detail/components/plan_header.dart
  lib/presentation/plan_detail/plan_detail_page.dart
  lib/presentation/plan_detail/plan_detail_page_notifier.dart
  lib/presentation/plan_detail/plan_detail_page_notifier.g.dart
  lib/presentation/plan_detail/plan_detail_page_state.dart
  lib/presentation/plan_detail/plan_detail_page_state.freezed.dart
Labels: 🎉 new feature

#262 多言語対応の各言語を対応した国の言語にリファクタする
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_ko.g.dart
  lib/i18n/strings_ko.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
Labels: 🧹 refactoring

#261 名前を登録しないユーザー名の処理
  lib/domain/entities/user.dart
  lib/domain/entities/user.freezed.dart
  lib/domain/entities/user.g.dart
  lib/presentation/mypage/components/account_status.dart
  lib/presentation/register_profile/register_profile_page_notifier.dart
  lib/presentation/sms_verification/sms_verification_page_notifier.dart
  lib/utils/providers/current_user/current_user.dart
Labels: 🎉 new feature

#269 プラン作成ページのリニューアル
  lib/domain/entities/plan_prompt.dart
  lib/domain/entities/plan_prompt.freezed.dart
  lib/domain/entities/plan_prompt.g.dart
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_en.g.dart
  lib/i18n/strings_ja.g.dart
  lib/i18n/strings_ja.i18n.json
  lib/i18n/strings_ko.g.dart
  lib/i18n/strings_ko.i18n.json
  lib/i18n/strings_zh-Hans.i18n.json
  lib/i18n/strings_zh-Hant.i18n.json
  lib/i18n/strings_zh_Hans.g.dart
  lib/i18n/strings_zh_Hant.g.dart
  lib/presentation/create_plan/components/number_of_people_selector.dart
  lib/presentation/create_plan/components/plan_text_field.dart
  lib/presentation/create_plan/components/schedule_selector.dart
  lib/presentation/create_plan/components/selection_modal.dart
  lib/presentation/create_plan/components/topic_chip_field.dart
  lib/presentation/create_plan/components/topic_text_field.dart
  lib/presentation/create_plan/components/transport_selector.dart
  lib/presentation/create_plan/create_plan_notifier.dart
  lib/presentation/create_plan/create_plan_notifier.g.dart
  lib/presentation/create_plan/create_plan_page.dart
  lib/presentation/create_plan/create_plan_state.dart
  lib/presentation/create_plan/create_plan_state.freezed.dart
  lib/utils/translate_prompt.dart
Labels: 🎉 new feature

#268 [Android]バージョン不一致のエラーを修正
  android/build.gradle
Labels: 🐛 bug fix, 📱Android

#274 geminiのバージョンダウン
  lib/infrastructure/gemini/gemini_data_source.dart
Labels: 🐛 bug fix
